window.WU_DATA = [
  {
    name: 'Pinterest', category: 'Content', tier: 'high',
    summary: 'Generative image tools now produce moodboard-ready visuals in seconds.',
    updated: '2 d ago',
    verdict: 'Pinterest\u2019s core loop \u2014 browse, save, curate \u2014 is being squeezed from both ends: generative models create board-ready imagery on demand, and users increasingly prompt rather than search.',
    evidence: [
      { type: 'AI capability benchmark', text: 'Leading image models now generate on-brand moodboards from a single prompt, matching the visual coherence of hand-curated boards in blind reviews.' },
      { type: 'User migration signal', text: 'App store reviews increasingly mention using AI image tools "instead of digging through Pinterest" for mood and style references.' },
      { type: 'Traffic/usage stats', text: 'Search-referral traffic to visual discovery platforms has softened as AI chat interfaces absorb more early-stage "what should this look like" queries.' },
    ],
    agree: 214, disagree: 61,
    related: [ { name: 'Goodreads', tier: 'high' }, { name: 'TikTok', tier: 'low' } ],
  },
  {
    name: 'Wikipedia', category: 'Knowledge', tier: 'medium',
    summary: 'Chatbots absorb lookup traffic, but sourcing and edit-trust remain a moat.',
    updated: '5 d ago',
    verdict: 'AI answer engines are intercepting the quick-lookup queries that used to land on Wikipedia, but the encyclopedia\u2019s edit history, citations, and human consensus process remain hard to replicate credibly.',
    evidence: [
      { type: 'Traffic/usage stats', text: 'Direct pageviews for quick-fact articles have trended down as AI assistants answer simple factual queries without a click-through.' },
      { type: 'AI capability benchmark', text: 'Language models still cite Wikipedia as a primary source for factual grounding \u2014 the site remains upstream of the tools replacing it.' },
      { type: 'User migration signal', text: 'Editors report steady contribution volume; the threat is to pageviews, not to the editing community itself.' },
    ],
    agree: 156, disagree: 98,
    related: [ { name: 'Goodreads', tier: 'high' }, { name: 'Reddit', tier: 'low' } ],
  },
  {
    name: 'Reddit', category: 'Community', tier: 'low',
    summary: 'Data-licensing deals and authentic discussion give Reddit real leverage.',
    updated: '1 d ago',
    verdict: 'Reddit\u2019s threads are exactly the messy, opinionated, human-authored data that AI labs pay to train on \u2014 a rare case where AI\u2019s hunger for content strengthens rather than threatens the platform.',
    evidence: [
      { type: 'Traffic/usage stats', text: 'Logged-in usage and time-on-site have held steady even as AI-generated content floods other platforms.' },
      { type: 'AI capability benchmark', text: 'Models remain weak at replicating in-community credibility signals like upvotes, tenure, and subreddit-specific norms.' },
      { type: 'User migration signal', text: 'No meaningful shift toward AI-only alternatives for community-vetted advice and discussion.' },
    ],
    agree: 302, disagree: 22,
    related: [ { name: 'Twitter / X', tier: 'medium' }, { name: 'LinkedIn', tier: 'medium' } ],
  },
  {
    name: 'Twitter / X', category: 'Social', tier: 'medium',
    summary: 'Bot-generated content dilutes the feed, but the real-time graph still matters.',
    updated: '3 d ago',
    verdict: 'AI-written posts and reply-bots have measurably diluted feed quality, yet breaking-news reflexes and the follow graph keep humans checking in during live events AI can\u2019t originate.',
    evidence: [
      { type: 'AI capability benchmark', text: 'Automated accounts can now sustain believable posting cadences, complicating the platform\u2019s authenticity signal.' },
      { type: 'Traffic/usage stats', text: 'Spikes in usage still cluster tightly around live events \u2014 breaking news, sports, launches \u2014 that AI cannot originate ahead of time.' },
      { type: 'User migration signal', text: 'Power users report increased muting/blocking of suspected bot activity rather than platform abandonment.' },
    ],
    agree: 178, disagree: 133,
    related: [ { name: 'Reddit', tier: 'low' }, { name: 'LinkedIn', tier: 'medium' } ],
  },
  {
    name: 'TikTok', category: 'Content', tier: 'low',
    summary: 'Algorithmic feed and creator culture remain far ahead of generative video.',
    updated: '6 d ago',
    verdict: 'Generative video is improving fast, but it\u2019s nowhere near TikTok\u2019s feed algorithm, sound culture, and creator economy \u2014 the platform\u2019s real moat isn\u2019t the clips, it\u2019s the loop.',
    evidence: [
      { type: 'AI capability benchmark', text: 'Text-to-video output still lacks the trend-aware timing and audio-sync that make clips spread on the platform.' },
      { type: 'Traffic/usage stats', text: 'Average session length continues to climb year over year, showing no engagement erosion.' },
      { type: 'User migration signal', text: 'Creator migration to AI-video tools is additive (used to make content) rather than substitutive (used to leave the platform).' },
    ],
    agree: 265, disagree: 40,
    related: [ { name: 'Pinterest', tier: 'high' }, { name: 'Reddit', tier: 'low' } ],
  },
  {
    name: 'Goodreads', category: 'Community', tier: 'high',
    summary: 'AI already writes better book summaries and recs than a stale review feed.',
    updated: '4 d ago',
    verdict: 'Goodreads\u2019s review database is aging and its recommendation engine is weak; AI reading assistants already produce sharper summaries and personalized recommendations with none of the site\u2019s clutter.',
    evidence: [
      { type: 'AI capability benchmark', text: 'AI assistants generate nuanced, spoiler-aware book summaries and comparisons on demand, outperforming the median user review.' },
      { type: 'User migration signal', text: 'Reading communities increasingly organize on newer apps and AI-assisted note-taking tools instead of legacy review sites.' },
      { type: 'Traffic/usage stats', text: 'Review submission volume has plateaued while alternative reading-tracking apps report growth.' },
    ],
    agree: 189, disagree: 54,
    related: [ { name: 'Wikipedia', tier: 'medium' }, { name: 'Pinterest', tier: 'high' } ],
  },
  {
    name: 'LinkedIn', category: 'Social', tier: 'medium',
    summary: 'AI-written posts are flooding feeds, but professional identity is sticky.',
    updated: '1 d ago',
    verdict: 'A visible share of feed content now reads as AI-generated "thought leadership," degrading feed quality \u2014 but the platform\u2019s role as a professional identity and recruiting graph is not easily replicated.',
    evidence: [
      { type: 'AI capability benchmark', text: 'Language models can produce on-brand professional posts indistinguishable from many human ones in casual review.' },
      { type: 'User migration signal', text: 'Recruiter and job-seeker usage remains concentrated on the platform despite feed-quality complaints.' },
      { type: 'Traffic/usage stats', text: 'Time spent on feed content is down slightly; time spent on messaging and job search functions is flat to up.' },
    ],
    agree: 141, disagree: 87,
    related: [ { name: 'Twitter / X', tier: 'medium' }, { name: 'Reddit', tier: 'low' } ],
  },
];
